name: Jira Update

on:
  push:

jobs:
  jira-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Jira for comments from develop branch...
        uses: dodevops/jira-cloud-github-action@main
        with:
          url: ${{ secrets.JIRA_BASE_URL }}
          username: ${{ secrets.JIRA_USER_EMAIL }}
          token: ${{ secrets.JgIRA_API_TOKEN }}